SELECT W.ID
        , WP.AGE
        , W.COINS_NEEDED
        , W.POWER
FROM WANDS W
LEFT JOIN WANDS_PROPERTY WP
    ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0
AND W.COINS_NEEDED = (
    SELECT MIN(W2.COINS_NEEDED)
    FROM WANDS W2
    LEFT JOIN WANDS_PROPERTY WP2 
        ON W2.CODE = WP2.CODE
    WHERE WP2.IS_EVIL = 0
    AND W2.POWER = W.POWER
    AND WP2.AGE = WP.AGE
)
ORDER BY W.POWER DESC, WP.AGE DESC;
