WITH CANDIDATES AS (
	SELECT CON.CONTEST_ID
		, CON.HACKER_ID
		, CON.NAME
		, COL.COLLEGE_ID
		, CHA.CHALLENGE_ID
	FROM CONTESTS CON
	LEFT JOIN COLLEGES COL
		ON CON.CONTEST_ID = COL.CONTEST_ID
	LEFT JOIN CHALLENGES CHA
		ON COL.COLLEGE_ID = CHA.COLLEGE_ID
)
, SUBMISSIONS_SUM AS (
	SELECT CAN.CONTEST_ID
		, SUM(COALESCE(TOTAL_SUBMISSIONS, 0)) TOTAL_SUBMISSIONS_SUM
		, SUM(COALESCE(TOTAL_ACCEPTED_SUBMISSIONS, 0)) TOTAL_ACCEPTED_SUBMISSION_SUM
	FROM CANDIDATES CAN
	LEFT JOIN SUBMISSION_STATS SUB
		ON CAN.CHALLENGE_ID = SUB.CHALLENGE_ID
	GROUP BY CONTEST_ID
)
, VIEWS_SUM AS (
	SELECT CAN.CONTEST_ID
		, SUM(COALESCE(TOTAL_VIEWS, 0)) AS TOTAL_VIEWS_SUM
		, SUM(COALESCE(TOTAL_UNIQUE_VIEWS, 0)) AS TOTAL_UNIQUE_VIEWS_SUM
	FROM CANDIDATES CAN
	LEFT JOIN VIEW_STATS VIE
		ON CAN.CHALLENGE_ID = VIE.CHALLENGE_ID
	GROUP BY CONTEST_ID
)
SELECT DISTINCT CAN.CONTEST_ID
	, HACKER_ID
	, NAME
	, TOTAL_SUBMISSIONS_SUM
	, TOTAL_ACCEPTED_SUBMISSION_SUM
	, TOTAL_VIEWS_SUM
	, TOTAL_UNIQUE_VIEWS_SUM
FROM CANDIDATES CAN
LEFT JOIN SUBMISSIONS_SUM SUB_SUM
	ON CAN.CONTEST_ID = SUB_SUM.CONTEST_ID
LEFT JOIN VIEWS_SUM VIE_SUM
	ON CAN.CONTEST_ID = VIE_SUM.CONTEST_ID
WHERE (TOTAL_SUBMISSIONS_SUM 
		+ TOTAL_ACCEPTED_SUBMISSION_SUM 
		+ TOTAL_VIEWS_SUM 
		+ TOTAL_UNIQUE_VIEWS_SUM) != 0
ORDER BY CONTEST_ID
