WITH FRIENDSHIP AS (
	SELECT FR.ID
		, ST.NAME
		, FR.FRIEND_ID
		, STS.NAME AS NAME_FR
	FROM FRIENDS FR
	LEFT JOIN STUDENTS ST
	ON FR.ID = ST.ID
	LEFT JOIN STUDENTS STS
	ON FR.FRIEND_ID = STS.ID
)
, SALARY_FRIEND AS (
	SELECT F.ID
		, NAME
		, P.SALARY
		, FRIEND_ID
		, NAME_FR
		, PS.SALARY AS SALARY_FR
		, CASE 
			WHEN P.SALARY < PS.SALARY 
			THEN 1 
			ELSE 0
		  END AS FG_HIGHER_SALARY
	FROM FRIENDSHIP F
	LEFT JOIN PACKAGES P
	ON F.ID = P.ID
	LEFT JOIN PACKAGES PS
	ON F.FRIEND_ID = PS.ID
)
SELECT NAME
FROM SALARY_FRIEND
WHERE FG_HIGHER_SALARY = 1
ORDER BY SALARY_FR